In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Generar una lista booleana que me diga quiénes cumplen con mi condición

In [4]:
index_cond = arr > 5
index_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Filtrar valores de nuestro array que cumplan nuestra condición, para varias condiciones de debe usar el operador &

In [5]:
arr[index_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [6]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Modificar datos de acuerdo a una condición también es posible

In [8]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)