In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tomar un trozo del array arr y cambiar todos sus valores por cero, datos originales de arr se sobreescribieron.

In [4]:
trozo_arr = arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [6]:
trozo_arr[:] = 0 #Cambiar todos los valores a cero
trozo_arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Generar una copia de arr con copy() evita que modifiquemos el array original

In [9]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
arr_copy[:] = 100
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])