In [16]:
import numpy as np

In [17]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

np.arrange(n,m,z) me genera un array desde n hasta m con un step de z

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

np.zeros((n,m)) me define un array de ceros de n por m

In [19]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

np.ones((n,m)) me define un array de unos de n por m

In [20]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

np.linspace(n,m,z) me genera una distribución de rango (n,m) con z cantidad de datos

In [21]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

np.eye(n) me genera una matriz de dimensión n*n cuya diagonal son unos y sus demás valores son cero

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.random.rand(n,m) generará un array de valores aleatorios entre 0 y 1 de dimensión n*m

In [23]:
np.random.rand(4,3)

array([[0.44043593, 0.64317408, 0.72376922],
       [0.42409585, 0.46497153, 0.39278497],
       [0.30421818, 0.89931526, 0.02561027],
       [0.79866567, 0.75513974, 0.19306487]])

np.random.randint(n,m, (x,z)) genera un array de dimensión x*z de valores aleatorio entre n y m. Si x y z son cero, genera un escalar.

In [24]:
np.random.randint(1,15,(10,10))

array([[ 9, 10,  6,  9,  3, 11,  3,  1,  4,  8],
       [ 1,  6, 11,  9,  3,  2,  2,  6, 11, 12],
       [10,  6, 12, 12, 13, 10,  2,  5,  3,  4],
       [ 2,  4, 14,  4, 12, 10,  2, 10, 14, 13],
       [ 5,  7,  4, 10,  4,  9, 11, 13, 14,  5],
       [ 6, 14, 14,  9, 12,  2,  6,  2,  3,  6],
       [ 3,  8,  6,  6,  2, 13, 11,  5,  7, 10],
       [ 3,  6, 13,  6, 13, 14,  5, 13, 13,  2],
       [ 7, 12,  2,  2,  9,  4, 10, 12, 14,  1],
       [12,  7, 12,  1,  3, 10,  7, 14,  8,  3]])