In [30]:
import numpy as np

# Dimensiones en numpy

In [31]:
scalar = np.array(10)
print(scalar)
scalar.ndim

10


0

In [32]:
vector = np.array([10, 20, 30])
print(vector)
vector.ndim

[10 20 30]


1

In [33]:
matrix = np.array([[10, 20, 30], [4, 5, 6], [8, 12, 16]])
print(matrix)
matrix.ndim

[[10 20 30]
 [ 4  5  6]
 [ 8 12 16]]


2

In [34]:
tensor = np.array([[[10, 20, 30], [4, 5, 6], [8, 12, 16]], [[1, 2, 3], [7, 8, 9], [10, 11, 12]]])
print(tensor)
tensor.ndim

[[[10 20 30]
  [ 4  5  6]
  [ 8 12 16]]

 [[ 1  2  3]
  [ 7  8  9]
  [10 11 12]]]


3

## Agregar o eliminar dimensiones

con ndmin = n obligo al array a tener n cantidad de dimensiones

In [35]:
vector = np.array([10, 20, 30], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[10 20 30]]]]]]]]]]


10

np.expand_dims sirve para expandir una dimensión, en este caso, axis = 0 significa que la voy a expandir a nivel de filas, axis = 1 significaría a nivel de columnas.

In [36]:
vector = np.expand_dims(np.array([10, 20, 30]), axis=0)
print(vector)
vector.ndim

[[10 20 30]]


2

Para eliminar las dimensiones uso np.squeeze, el cual me redimensiona mi array a lo que sea considerado necesario (elimina dimensiones vacías)

In [37]:
vector = np.array([10, 20, 30], ndmin=10)
print(vector, vector.ndim)

vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[10 20 30]]]]]]]]]] 10
[10 20 30] 1
