In [118]:
import numpy as np

In [119]:
list = [1, 2, 3, 4, 5, 6, 7, 8 ,9]
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


Convierto la lista a un array

In [120]:
arr = np.array(list)
print(arr)

[1 2 3 4 5 6 7 8 9]


Convierto la matriz a un array

In [121]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
arr_2 = np.array(matriz)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [122]:
arr[1]

2

In [123]:
arr[0]

1

In [124]:
arr[0]+arr[1]

3

In [125]:
arr_2[0]

array([1, 2, 3])

Navego entre los elementos de la matriz, por ejemplo, con arr_2[0,2] navego al primer elemento de la matriz [1,2,3] y a la tercera posición [3]

In [126]:
arr_2[0, 2]

3

Con los dos puntos : puedo hacer slices, de tipo arr[valor inicial : valor final]

In [127]:
arr[:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
arr[:9:3]

array([1, 4, 7])

Un número negativo me va a traer las posiciones pero de atrás hacia adelante

In [129]:
arr[-3]

7

En este caso, estamos seleccionando filas desde el índice 1 hasta el final y columnas desde el índice 0 hasta el índice 2 (pero excluyendo el índice 1 en ambos casos).

In [130]:
arr_2[1:,0:2]

array([[4, 5],
       [7, 8]])

# Ejercicio: Matriz de 3D (tensor)

In [131]:
matriz3D = [[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]]
arr3D = np.array(matriz3D)
arr3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [132]:
arr3D[0,0:,0:2]

array([[1, 2],
       [4, 5]])