In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)

array([12, 19,  1, 15,  1,  8,  2,  4,  8,  8])

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[12, 19,  1, 15,  1],
       [ 8,  2,  4,  8,  8]])

Función max(n) me retorna el valor máximo de una matriz por fila (n = 1) o por columa (n=0). Si n no se indica, será el valor máximo total

In [6]:
arr.max()

19

In [8]:
matriz.max(1)

array([19,  8])

matriz.argmax(n) nos da el menor índice en donde se encuentra el valor máximo de nuestro array, si n=1 entonces se hará por filas, si n=2 se hará por columas

In [11]:
matriz.argmax(1)

array([1, 0])

Función min(n) funciona como max(n) pero con el valor mínimo

In [12]:
matriz.min(0)

array([8, 2, 1, 8, 1])

In [13]:
matriz.argmin(1)

array([2, 1])

La función ptp() nos muestra la diferencia entre el valor máximo y el valor mínimo en el array.

In [15]:
matriz.ptp()

18

np.percentile(arr, n) nos da el percentil n del array arr. La función sort() nos ordena los valores de menor a mayor

In [20]:
arr.sort()

In [19]:
np.percentile(arr, 50)

8.0

Medidas de tendencia central y de dispersión

In [22]:
np.median(matriz, 0)

array([ 4.5,  4.5,  7. ,  9.5, 13.5])

In [25]:
np.mean(arr)

7.8

In [23]:
np.std(arr)

5.793099343184095

In [24]:
np.var(arr)

33.559999999999995

Se pueden unir dos arrays por medio de la concatenación. T es la transpuesta de la matriz.

In [30]:
a = np.array([[1,2], [3,4]]) #Dos dimensions
b= np.array([5, 6]) #Una dimensión
b = np.expand_dims(b, axis = 0) #Expandir b a dos dimensiones a lo largo del eje 0 para que no me genere error
np.concatenate((a,b.T), axis = 1) #Se concatenan ambos arrays a lo largo del eje 1 de dimensiones iguales cambiando la forma de b

array([[1, 2, 5],
       [3, 4, 6]])