In [12]:
import numpy as np

In [13]:
lista = [1, 2]
lista

[1, 2]

Aplicar a los valores de la lista una operación matemática

In [14]:
lista * 2 #duplica la lista, no multipica sus valores

[1, 2, 1, 2]

In [15]:
arr = np.arange(0, 10)
arr2 = arr.copy()

In [16]:
arr * 2 #Esta vez sí se multiplican los valores por 2 al usar un array y no una lista

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
1/arr

/tmp/ipykernel_19961/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [18]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

¿Y si tenemos una matriz?

In [19]:
matriz = arr2.reshape(2, 5)
matriz2 = matriz.copy()

In [20]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

La expresión np.matmul(matriz, matriz2.T) realiza la multiplicación matricial (producto punto) entre la matriz matriz y la transpuesta de la matriz matriz2.

In [22]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])