In [32]:
import numpy as np

# Modificar arrays y saber su forma

In [33]:
arr = np.random.randint(1,10,(3,2))
print(arr)

[[9 1]
 [7 7]
 [2 9]]


arr.shape me da la dimensión del arreglo "arr"

In [34]:
arr.shape

(3, 2)

arr.reshape(n,m) me cambia la forma de "arr" a un array de n*m

In [35]:
arr.reshape(2,3)

array([[9, 1, 7],
       [7, 2, 9]])

np.reshape(array,(n,m), 'lenguaje') es otra sintaxis que hace lo mismo que la anterior, si añadimos 'lenguaje' me lo ordena con base en un lenguaje: C, F (fortran) y A (como mejor esté optimizado el almacenamiento del sistema).

In [36]:
np.reshape(arr,(1,6))

array([[9, 1, 7, 7, 2, 9]])

In [37]:
np.reshape(arr,(2,3),'C')

array([[9, 1, 7],
       [7, 2, 9]])

In [38]:
np.reshape(arr,(2,3),'F')

array([[9, 2, 7],
       [7, 1, 9]])

In [39]:
np.reshape(arr,(2,3),'A')

array([[9, 1, 7],
       [7, 2, 9]])

# Reto: reshape a un tensor

In [41]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Usar np.reshape(tensor,(x,y,z)) convierte mi tensor en uno de 3 dimensiones x * y * z

In [61]:
tensor_reshape = np.reshape(tensor,(2,4,1))
print(tensor_reshape)
print(tensor_reshape.ndim)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]
3
