In [15]:
import numpy as np

In [16]:
arr = np.random.randint(1,10,(3,2))
print(arr)

[[1 1]
 [8 2]
 [5 2]]


arr.shape me da la dimensión del arreglo "arr"

In [17]:
arr.shape

(3, 2)

arr.reshape(n,m) me cambia la forma de "arr" a un array de n*m

In [18]:
arr.reshape(2,3)

array([[1, 1, 8],
       [2, 5, 2]])

np.reshape(array,(n,m), 'lenguaje') es otra sintaxis que hace lo mismo que la anterior, si añadimos 'lenguaje' me lo ordena con base en un lenguaje: C, F (fortran) y A (como mejor esté optimizado el almacenamiento del sistema).

In [19]:
np.reshape(arr,(1,6))

array([[1, 1, 8, 2, 5, 2]])

In [20]:
np.reshape(arr,(2,3),'C')

array([[1, 1, 8],
       [2, 5, 2]])

In [21]:
np.reshape(arr,(2,3),'F')

array([[1, 5, 2],
       [8, 1, 2]])

In [22]:
np.reshape(arr,(2,3),'A')

array([[1, 1, 8],
       [2, 5, 2]])