In [20]:
import numpy as np

In [21]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

Cambio el dtype a float (mejor para redes neuronales)

In [22]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [23]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.float64)
arr

array([0., 1., 2., 3., 4.])

Cambiar a booleano

In [24]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

Cambiar a string

In [25]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

Csmbiar a int8

In [26]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)